### ISSUE TITLE
Front session middleware error

### ISSUE THREAD

**Issue by RoboTeddy** [buttercoin/buttercoin#19]
Steps to reproduce:
1. run ./start.sh
2. visit http://localhost:3000

I don't have any cookies. Commenting out `app.use(express.session({ store: store, secret: secret, key: 'sid' }))` stops the exception from happening.

```
› killall -9 node; ./start.sh                                                                                                                     1
No matching processes belonging to you were found
engine: Buttercoin trading engine started
info: Buttercoin api server started on ws://0.0.0.0:3001
SockJS v0.3.5 bound to "/sock"
info: Buttercoin front-end server started on http://0.0.0.0:3000
GET /sock/info 1ms 200
GET /sock/657/8qjh2rk6/websocket 0ms (unfinished)
warn: front attempting to log in to ws://localhost:3001
info: api server receiving incoming wss connection from localhost:3001
info: front connected to ws://localhost:3001
info: front 24654 received message: i am api server 24653
info: api server 24653 received message: i am front-end 24654
TypeError: Cannot read property 'sid' of undefined
    at Object.session [as handle] (/Users/ted/Projects/buttercoin/node_modules/connect/lib/middleware/session.js:238:32)
    at next (/Users/ted/Projects/buttercoin/node_modules/connect/lib/proto.js:190:15)
    at resume (/Users/ted/Projects/buttercoin/node_modules/connect/lib/middleware/static.js:60:7)
    at SendStream.error (/Users/ted/Projects/buttercoin/node_modules/connect/lib/middleware/static.js:73:37)
    at SendStream.EventEmitter.emit (events.js:126:20)
    at SendStream.error (/Users/ted/Projects/buttercoin/node_modules/connect/node_modules/send/lib/send.js:147:51)
    at SendStream.onStatError (/Users/ted/Projects/buttercoin/node_modules/connect/node_modules/send/lib/send.js:248:48)
    at SendStream.pipe (/Users/ted/Projects/buttercoin/node_modules/connect/node_modules/send/lib/send.js:320:26)
    at Object.oncomplete (fs.js:297:15)
```

**Comment by Marak** [comment]
Seem to be fixed now. Closing.
