### ISSUE TITLE
Buttercoin Couldn't Deply on Debian 7.3 (wheezy) 32 bit: Worth looking at the code?

### ISSUE THREAD

**Issue by inrazhtet** [buttercoin/buttercoin#66]
Hello,
I have tried to deploy Buttercoin on Debian and starting from npm test, I am seeing the following issues. What I would like to know is whether it is worth the time to look at the code myself and try to figure it out. (I have very little experience with node.js).
There is nothing on localhost:3000. I tried localhost:3001, localhost:3002, localhost:6151 and 6152 which has the sign "not implemented".
Thanks a lot!
Zarni

buttercoin@0.0.3 test /root/buttercoin
sh test.sh
/root/buttercoin/test/test_helper.coffee:1
xports, require, module, __filename, __dirname) { global.chai = require 'chai'
^^^^^^
SyntaxError: Unexpected string
at Module.compile (module.js:439:25)
at Object.Module.extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module.load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at files (/root/buttercoin/nodemodules/mocha/bin/mocha:271:3)
at Array.forEach (native)
at Object. (/root/buttercoin/nodemodules/mocha/bin/mocha:270:10)
at Module.compile (module.js:456:26)
at Object.Module.extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module.load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:902:3

**Comment by Ryaan** [comment]
I have the same issue
